name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read
  security-events: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high  
          token: ${{ secrets.PAT_DEPENDABOT }}
