name: Dependency Review

on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run dependency review
      uses: actions/dependency-review-action@v4
      with:
        repo-token: ${{ secrets.PAT_DEPENDABOT }}
        fail-on-severity: high
        fail-on-scopes: runtime
