name: Security Scan with Trivy

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  security-events: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.28
